### PR TITLE
Freebsd current based on pr 51

### PR DESCRIPTION
**Pull request by masatake**
This is based on #51 made by @ lrosenman.

* Simplify the commit sequence.
* Add prefix [freebsd] to some logs.
* Split the commits about cirrus.

### CODE REVIEW

**Comment by masatake** [comment]
@lrosenman, please, review this and merge if there is no issue.

**Comment by lrosenman** [comment]
@masatake do I need to worry about the coveralls failure?

**Comment by masatake** [comment]
> @masatake do I need to worry about the coveralls failure?

Yes. The coverage is measured in linux on travis. So adding new code for freebsd always reduces the percentage.

**Comment by masatake** [comment]
Next time, please merge after travis and cirrus say o.k.
(The testing on FreeBSD was not finished when you merged)

**Comment by masatake** [comment]
Thank you.

**Comment by lrosenman** [comment]
Noted.  (I knew it would pass as it passed on my PR, but understood).

**Comment by masatake** [comment]
I forgot to write one important thing.
As far as reading https://reviews.freebsd.org/D20341, cem (Conrad Meyer) is the original author of 0589482. Am I wrong?

If yes, we should write it in the commit log. However, it should not rewrite the history after merging.
So I think, writing it in 00CREDIT and 00DIST will be better.

**Comment by lrosenman** [comment]
He (Conrad) is already in 00CREDIT as a contributor, do we need to add it to the commit (future...) that he authored the change?

**Comment by lrosenman** [comment]
And he wrote the dlsof.h change, I wrote the Configure change to quiet a warning.

**Comment by masatake** [comment]
> He (Conrad) is already in 00CREDIT as a contributor, do we need to add it to the commit (future...) that he authored the change?

Oh, I see. Putting 00CREDIT is enough I think. Thank you.

**Pull request merged**
