### PR TITLE
[linux] Avoid some easy collissions for udp/udp6 sockets when hashing

### PR DESCRIPTION
**Pull request by BenBE**
As promised in #208 here's that minor hash function change.

The values in the change are chosen in a way that similar values from different components that make up the hash are added with a slight shift relative to each other.

### CODE REVIEW

**Review by masatake — APPROVED** [review]

**Comment by masatake** [comment]
@dilinger do you have a comment?

**Comment by BenBE** [comment]
One comment I might add from my side is, that hashtables usually work best, when buckets are rarely hit. While debugging this I had a brief look into the raw data and saw, that `/proc/net/sockstat` reported >2200 used sockets on a moderately active system. With a hashmap size of 128 for the socket information this gives approx 20 sockets per bucket. Even when assuming an even distribution this causes the linear search aspect of the map implementation to be noticeable. Increasing the hashmap size to e.g. 4096 entries should mitigate this.

**Comment by dilinger** [comment]
No comment, I'd have to really dig into it and don't have time right now. Sorry!

**Comment by masatake** [comment]
Thank you!

**Pull request merged**
