### PR TITLE
Add support for O_CLOEXEC flag on Linux

### PR DESCRIPTION
**Pull request by barsnick**
Closes lsof-org/lsof#38

### CODE REVIEW

**Comment by masatake** [comment]
Do you think `#if	defined(O_CLOEXEC)` is needed here?

**Comment by barsnick** [comment]
I would say so. I don't have any old Linux kernel anymore, but the docs say
```since Linux 2.6.23```. There used to be some yet-available legacy LTS distributions which still used 2.6.16, but those days may be over. Consider non-availability of this define an "old dialect" - it might just happen.

**Comment by masatake** [comment]
I looked into strace to know how strace handles these case.
strace also use "#if defined O_CLOEXEC".
I will add the condition to  my patch.
Thank you.

**Comment by masatake** [comment]
#40 does the same.

**Pull request closed without merging**
