### PR TITLE
FreeBSD: retire support for long-obsolete FreeBSD versions

### PR DESCRIPTION
**Pull request by emaste**

### CODE REVIEW

**Review by lrosenman — APPROVED** [review]

**Comment by masatake** [comment]
@lrosenman could you update 00DIST and 00CREDITS for this change?

**Comment by emaste** [comment]
FWIW I am already listed in 00CREDITS, only 00DIST needs updating

**Comment by lrosenman** [comment]
Done :)

**Comment by masatake** [comment]
Thank you.

**Pull request merged**
