### PR TITLE
[freebsd] fix badges to refer to the correct repo

### LINKED ISSUE #57: freebsd13 badge not working?
@masatake are we missing something in the README.md to show the current badges?

https://cirrus-ci.com/build/4679280974364672

shows all 3 FreeBSD runs passing, but the link doesn't show PR's since 26. 

Just wondering....

### PR DESCRIPTION
**Pull request by lrosenman**
refer to the correct repo.  Should fix #57

### CODE REVIEW

**Comment by masatake** [comment]
Other than merging, we have no way to know whether your changes work well or not.
Introducing a test branch (e.g. badge-testing-tmp) at lsof-org/lsof repo, and merge your change to the branch. Then, open https://github.com/lsof-org/lsof with your web browser, and choose the branch from the popup menu in the page.  You can see whether the badges are shown expectedly (or not).

**Comment by masatake** [comment]
These change should be squashed into one commit.

**Comment by lrosenman** [comment]
Actually, we do know they work, if you look at
https://github.com/lrosenman/lsof

it expands out.

**Comment by lrosenman** [comment]
I think that it's now squashed...

**Comment by masatake** [comment]
Looks fine.
This PR includes only one change. So using "Rebase and merge" method for merging is better.
(See the pop up menu beside "Merge pull request" button.)

**Comment by masatake** [comment]
It seems that your commits are not squashed into one.
cbdfe55 is just appended.

**Comment by lrosenman** [comment]
I'm not sure how to do it then....




Get Outlook for Android







On Sat, Jun 1, 2019 at 11:28 AM -0500, "Masatake YAMATO" <notifications@github.com> wrote:












It seems that your commits are not squashed into one.

cbdfe55 is just appended.

**Comment by masatake** [comment]
BTW, you should not use "master" branch of your lrosenman/lsof repository to make a pull request.
Your master branch is for synchronizing  the commits at master branch of lsof-org/lsof.
You should use a branch for each topic.

Here is what I wrote in my .git/cofig:
```
[remote "origin"]
	url = git@github.com:masatake/lsof-legacy.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[remote "upstream"]
	url = https://github.com/lsof-org/lsof.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
```
.

When I want to fix FOO in lsof, I will do with the above config:
1. git checkout master
2. git pull upstream master:master
3. git checkout -b fix-or-enhance-FOO
4.  edit & commit 
5. git push origin fix-or-enhance-FOO:fix-or-enhane-FOO
6. make a pull request on lsof-org/lsof web page at  github
7. (Getting review comments)
8. "add more commits and git push"; or "add more commits , rearrange commits with "git rebase -i master", and git push --force.

To follow the above git workflow, you must clean up your master branch because your master branch already includes unwanted commits.

0.1. git checkout master
0.2. git branch -m freebsd-cirrus-badge
0.3. git checkout upstream/master
0.4. git checkout -b master (this step creates new clean "master" branch)
0.5 git pull upstream master:master
0.6 git checkout  freebsd-cirrus-badge
0.7 git rebase master 
      If conflicts are found in this step, you can do "git rebase --abort" to abort this step.

**Comment by masatake** [comment]
Before working this topic, I recommend you to clean up your master branch at your local pc and your master branch at github.

Then, make a branch for this topic from the master branch.
The change it self is not so long. So you can make a commit for this topic manually instead of rebasing the original branch.

**Comment by lrosenman** [comment]
closed in deference to #59

**Pull request closed without merging**
