### PR TITLE
FreeBSD isofs fixes and msdosfs support

### PR DESCRIPTION
**Pull request by DamjanJovanovic**
Fixes for the ISO9660 filesystem. Adds support for msdosfs.

### CODE REVIEW

**Comment by masatake** [comment]
I'm the maintainer of linux dialect. @lrosenman, the maintainer of FreeBSD dialect may review your changes.

Dialect independent comments:

Could you add "freebsd: " as the prefix for the commit headers like:
```
freebsd: the ISO9660 filesystem broke starting with FreeBSD 7 due to the header
freebsd: add support
```

In addition, could you add entries at the end of [00DIST](https://github.com/lsof-org/lsof/blob/master/00DIST)?

**Comment by DamjanJovanovic** [comment]
Thank you, I've changed the commit messages and updated 00DIST.

@lrosenman please also add more of the patches from the sysutils/lsof port. At least the namecache patch is needed on FreeBSD 12.2, otherwise lsof just hangs.

**Comment by masatake** [comment]
I am not sure whether this works well or not.
However, merging may be better to get feedback from users.
Let's see what happens.

**Comment by DamjanJovanovic** [comment]
> I am not sure whether this works well or not.
> However, merging may be better to get feedback from users.
> Let's see what happens.

Thank you :)

**Comment by masatake** [comment]
I'm sorry to take a long time.

**Pull request merged**
