### PR TITLE
Update perl scripts for the past few decades of progress

### PR DESCRIPTION
**Pull request by dilinger**
Generally, perl is available on base systems - people who are manually
installing perl into /usr/local/bin are the exception rather than the
rule. In addition, Perl 5 was release in 1994, so Perl 4 isn't relevant
any more. We've also standardized on the .pl extension, rather than
.perl5 or whatever.

Debian has been carrying a variant of this patch for a long time. I'd
like to just fix this upstream.

### CODE REVIEW

**Review by masatake — APPROVED** [review]

**Comment by masatake** [comment]
Thank you.
Please wait for awhile till merging.

**Comment by dilinger** [comment]
I've got other stuff to send upstream, but that's all for this branch & pull request.

**Comment by masatake** [comment]
Thank you very much. Especially about well-written commit logs and well-devided commits in purpose-by-purpose.

I have a request for planed pull requests.
Could you update 00DIST if your change includes user visible change?

**Comment by dilinger** [comment]
> I have a request for planed pull requests.
> Could you update 00DIST if your change includes user-visible change like [a509eb2](https://github.com/lsof-org/lsof/commit/a509eb285ca238ee6b67106c06ec7276e5c1ba11) ?
> 
> If your change includes or based on another person's work, I would like to add the one's name to 00CREDITS.

Will do! Thanks for merging.

**Pull request merged**
