### PR TITLE
oflags related enhancements ported from lsof-linux repo

### PR DESCRIPTION
**Pull request by masatake**

### CODE REVIEW

**Comment by masatake** [comment]
@barsnick, could you try this?

**Comment by barsnick** [comment]
Regarding issue #38: This works.

OTOH, I can't run the tests:
```
[barsnick@paradise lsof-legacy]$ make test
make: *** No rule to make target 'test'.  Stop.
[barsnick@paradise lsof-legacy]$ (cd tests/ && make test)
`cat config.cc`  -I. -I.. `cat config.cflags` LTbasic.c \
LTlib.o `cat config.xobj` -o LTbasic
/usr/bin/ld: LTlib.o: in function `ConvLsofDev':
LTlib.c:(.text+0xf8): undefined reference to `major'
/usr/bin/ld: LTlib.c:(.text+0x12e): undefined reference to `minor'
/usr/bin/ld: LTlib.o: in function `ConvStatDev':
LTlib.c:(.text+0x197): undefined reference to `major'
/usr/bin/ld: LTlib.c:(.text+0x1b3): undefined reference to `minor'
collect2: error: ld returned 1 exit status
make: *** [Makefile:74: LTbasic] Error 1
```
Dialect:
```
[barsnick@paradise lsof-legacy]$ uname -r
5.0.7-200.fc29.x86_64
[barsnick@paradise lsof-legacy]$ rpm -q glibc
glibc-2.28-27.fc29.x86_64
```

On a different platform, I get:
```
barsnick@hostname:/usr/new/system/lsof-legacy > (cd tests/ && make test)
`cat config.cc`  -I. -I.. `cat config.cflags` -c LTlib.c \
        -o LTlib.o
`cat config.cc`  -I. -I.. `cat config.cflags` LTbasic.c \
        LTlib.o `cat config.xobj` -o LTbasic
`cat config.cc`  -I. -I.. `cat config.cflags` LTnlink.c \
        LTlib.o `cat config.xobj` -o LTnlink
`cat config.cc`  -I. -I.. `cat config.cflags` LTsock.c \
        LTlib.o `cat config.xobj` -o LTsock `cat config.ldflags`
`cat config.cc`  -I. -I.. `cat config.cflags` LTszoff.c \
        LTlib.o `cat config.xobj` -o LTszoff
`cat config.cc`  -I. -I.. `cat config.cflags` LTunix.c \
        LTlib.o `cat config.xobj` -o LTunix `cat config.ldflags`

==================================================================

!!!WARNING!!!

This dialect or its particular version may not have been validated
with the lsof test suite.  Consequently some tests may fail or may
not even compile.

This is the computed identity of this dialect, not found in the
test data base file, ./TestDB:

    LT_BIGF LT_CC LT_DIAL_linux LT_VERS=26027 _FILE_OFFSET_BITS=64

Do you want to continue (y|n) [n]? y

Basic test:
LTbasic ... OK

Standard tests:
LTnlink ... OK
LTsock ... OK
LTszoff ... OK
LTunix ... OK
All standard tests succeeded.

Suggestion: try the optional tests: "make opt"

barsnick@sunshine:/usr/new/system/lsof-legacy > (cd tests/ && make opt)
`cat config.cc`  -I. -I.. `cat config.cflags` LTbigf.c \
        LTlib.o `cat config.xobj` -o LTbigf
`cat config.cc`  -I. -I.. `cat config.cflags` LTdnlc.c \
        LTlib.o `cat config.xobj` -o LTdnlc
`cat config.cc`  -I. -I.. `cat config.cflags` LTlock.c \
        LTlib.o `cat config.xobj` -o LTlock
`cat config.cc`  -I. -I.. `cat config.cflags` LTnfs.c \
        LTlib.o `cat config.xobj` -o LTnfs

Optional tests:
LTbigf ... OK
LTdnlc ... /usr/local/new/system/lsof-legacy/tests found: 100.00%
           OK
LTlock ... OK
LTnfs ... ERROR!!!  test file ./config.LTnfs30017 not found by lsof
          Hint: the temporary path generated by this test might
          not be on an NFS file system, or this test might be
          unable to create a file on the NFS file system.

          As a work-around use the -p option to specify a path to
          a regular file (not a directory) on an NFS file system
          to which this test will have read access.

          See 00FAQ and 00TEST for more information.
Failed tests: 1
```
This is okay, correct?
This is 2.6.27.41-170.2.117.fc10.i686, glibc-2.9 (ancient, I know).

**Comment by masatake** [comment]
> LTlib.c:(.text+0xf8): undefined reference to `major'

This must be fixed. I made a pull request.

> LTnfs ... ERROR!!!  test file ./config.LTnfs30017 not found by lsof
 > ...

NFS may be needed. I have inspect this yet. On travis-CI, currently I make the test case be skipped.
See tests/case-14-classic-opt.bash.

**Comment by masatake** [comment]
Thank you for testing.

**Comment by masatake** [comment]
I found I already put #ifdef/#endif for constants.
I didn't do so in test cases. I will consider it when we get an bug report that the test case cannot be compiled.

**Pull request merged**
